import { Document, Paragraph, TextRun, HeadingLevel, Packer, AlignmentType } from "docx";
import jsPDF from "jspdf";
import { useBrainSession } from "@/hooks/useBrainSession";
import { applyPdfTrimGuard } from "@/lib/pdfExport";

export type SessionState = ReturnType<typeof useBrainSession>["state"];

export function buildMarkdown(state: SessionState): string {
  return [
    `# Litigant AI Session Report`,
    ``,
    `**Question:** ${state.question}`,
    state.template ? `**Template:** ${state.template.title}` : null,
    `**Confidence:** ${state.confidence}%`,
    `**Credits Used:** ${state.creditsUsed}`,
    `**Date:** ${new Date().toLocaleDateString()}`,
    ``,
    `---`,
    ``,
    `## Final Answer`,
    ``,
    state.finalAnswer || "_No final answer generated._",
    ``,
    `---`,
    ``,
    `## Artifacts`,
    ``,
    state.artifacts || "_No artifacts generated._",
    ``,
    `---`,
    ``,
    `## Debate Notes`,
    ``,
    state.debateNotes || "_No debate notes._",
    ``,
    `---`,
    ``,
    `## Sources & Caveats`,
    ``,
    state.caveats,
    ``,
    `---`,
    `*Generated by Litigant AI — Don't just ask AI. Put the question on trial.*`,
  ].filter(Boolean).join("\n");
}

export function exportPDF(state: SessionState, w: Window): void {
  const esc = (s: unknown): string =>
    String(s ?? "").replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string)
    );

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Litigant AI Session — ${esc(state.question.slice(0, 60))}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; color: #111; line-height: 1.6; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }
    .meta { color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }
    pre { background: #f5f5f5; padding: 1rem; border-radius: 6px; white-space: pre-wrap; font-size: 0.8rem; }
    .badge { display: inline-block; background: #00c853; color: #000; font-size: 0.75rem; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Litigant AI Session Report</h1>
  <div class="meta">
    <strong>Question:</strong> ${esc(state.question)}<br/>
    ${state.template ? `<strong>Template:</strong> ${esc(state.template.title)}<br/>` : ""}
    <strong>Confidence:</strong> <span class="badge">${esc(state.confidence)}%</span>
    &nbsp; <strong>Credits:</strong> ${esc(state.creditsUsed)}
    &nbsp; <strong>Date:</strong> ${esc(new Date().toLocaleDateString())}
  </div>
  <h2>Final Answer</h2>
  <pre>${esc(state.finalAnswer || "No final answer generated.")}</pre>
  ${state.artifacts ? `<h2>Artifacts</h2><pre>${esc(state.artifacts)}</pre>` : ""}
  <h2>Debate Notes</h2>
  <pre>${esc(state.debateNotes || "No debate notes.")}</pre>
  <h2>Sources &amp; Caveats</h2>
  <pre>${esc(state.caveats)}</pre>
  <p style="margin-top:2rem;color:#999;font-size:0.75rem;">Generated by Litigant AI — Don't just ask AI. Put the question on trial.</p>
</body>
</html>`;

  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 400);
}

export async function exportDocx(state: SessionState): Promise<void> {
  const sections: Paragraph[] = [
    new Paragraph({ text: "Litigant AI Session Report", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({
      children: [
        new TextRun({ text: "Question: ", bold: true }),
        new TextRun({ text: state.question }),
      ],
    }),
    ...(state.template
      ? [new Paragraph({ children: [new TextRun({ text: "Template: ", bold: true }), new TextRun({ text: state.template.title })] })]
      : []),
    new Paragraph({
      children: [
        new TextRun({ text: "Confidence: ", bold: true }),
        new TextRun({ text: `${state.confidence}%` }),
        new TextRun({ text: "   Credits Used: ", bold: true }),
        new TextRun({ text: String(state.creditsUsed) }),
        new TextRun({ text: "   Date: ", bold: true }),
        new TextRun({ text: new Date().toLocaleDateString() }),
      ],
    }),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Final Answer", heading: HeadingLevel.HEADING_2 }),
    ...(state.finalAnswer || "No final answer generated.")
      .split("\n")
      .map((line) => new Paragraph({ text: line, alignment: AlignmentType.LEFT })),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Artifacts", heading: HeadingLevel.HEADING_2 }),
    ...(state.artifacts || "No artifacts generated.")
      .split("\n")
      .map((line) => new Paragraph({ text: line })),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Debate Notes", heading: HeadingLevel.HEADING_2 }),
    ...(state.debateNotes || "No debate notes.")
      .split("\n")
      .map((line) => new Paragraph({ text: line })),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Sources & Caveats", heading: HeadingLevel.HEADING_2 }),
    ...(state.caveats || "")
      .split("\n")
      .map((line) => new Paragraph({ text: line })),
    new Paragraph({ text: "" }),
    new Paragraph({
      children: [new TextRun({ text: "Generated by Litigant AI — Don't just ask AI. Put the question on trial.", italics: true, color: "888888" })],
    }),
  ];

  const doc = new Document({ sections: [{ children: sections }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `brain-session-${Date.now()}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportJsPdf(state: SessionState): { wasTrimmed: boolean } {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addText(
    text: string,
    opts: { size?: number; bold?: boolean; color?: [number, number, number]; wrap?: boolean; gap?: number } = {}
  ) {
    const { size = 10, bold = false, color = [20, 20, 20], wrap = true, gap = 4 } = opts;
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines: string[] = wrap ? doc.splitTextToSize(text || "", contentW) : [text];
    lines.forEach((line: string) => {
      if (y + 6 > pageH - margin) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += size * 0.45;
    });
    y += gap;
  }

  function addSection(title: string, body: string) {
    if (y + 20 > pageH - margin) { doc.addPage(); y = margin; }
    addText(title, { size: 12, bold: true, color: [0, 150, 60], gap: 2 });
    doc.setDrawColor(0, 150, 60);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 3;
    addText(body || "—", { size: 9.5, color: [40, 40, 40], gap: 6 });
  }

  addText("Litigant AI — Session Report", { size: 18, bold: true, color: [0, 150, 60], gap: 2 });
  addText(`Confidence: ${state.confidence}%  ·  Credits: ${state.creditsUsed}  ·  ${new Date().toLocaleDateString()}`, {
    size: 9, color: [100, 100, 100], gap: 6,
  });
  addText(`Question: ${state.question}`, { size: 10, bold: true, gap: 8 });

  const { safeText: safeAnswer, wasTrimmed } = applyPdfTrimGuard(state.finalAnswer || "No final answer generated.");
  addSection("Final Answer", safeAnswer);
  if (state.artifacts) addSection("Artifacts", state.artifacts);
  addSection("Debate Notes", state.debateNotes || "No debate notes.");
  addSection("Sources & Caveats", state.caveats || "");

  const slug = state.question.slice(0, 40).replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`litigant-ai-${slug}-${Date.now()}.pdf`);
  return { wasTrimmed };
}
