import { sessionOutput } from "@/lib/sessionOutput";
import { confidenceLabel } from "@workspace/api-zod/session";
import type { Paragraph as DocParagraph } from "docx";

import { useBrainSession } from "@/hooks/useBrainSession";
import { applyPdfTrimGuard } from "@/lib/pdfExport";

export type SessionState = ReturnType<typeof useBrainSession>["state"];

export function buildMarkdown(state: SessionState): string {
  return [
    `# Litigant AI Session Report`,
    ``,
    `**Question:** ${state.question}`,
    state.template ? `**Template:** ${state.template.title}` : null,
    `**AI review:** ${confidenceLabel(state.confidence)}`,
    `**Credits Used:** ${state.creditsUsed}`,
    `**Date:** ${new Date().toLocaleDateString()}`,
    ``,
    `---`,
    ``,
    ...sessionOutput(state).sections.map(section => `## ${section.title}\n\n${section.content}\n\n---`),
    `*Generated by Litigant AI — Don't just ask AI. Put the question on trial.*`,
  ].filter(Boolean).join("\n");
}

export function exportPDF(state: SessionState, w: Window): void {
  const esc = (s: unknown): string =>
    String(s ?? "").replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string)
    );

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Litigant AI Session — ${esc(state.question.slice(0, 60))}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; color: #111; line-height: 1.6; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }
    .meta { color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }
    pre { background: #f5f5f5; padding: 1rem; border-radius: 6px; white-space: pre-wrap; font-size: 0.8rem; }
    .badge { display: inline-block; background: #00c853; color: #000; font-size: 0.75rem; padding: 2px 8px; border-radius: 4px; font-weight: 600; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>Litigant AI Session Report</h1>
  <div class="meta">
    <strong>Question:</strong> ${esc(state.question)}<br/>
    ${state.template ? `<strong>Template:</strong> ${esc(state.template.title)}<br/>` : ""}
    <strong>AI review:</strong> <span class="badge">${esc(confidenceLabel(state.confidence))}</span>
    &nbsp; <strong>Credits:</strong> ${esc(state.creditsUsed)}
    &nbsp; <strong>Date:</strong> ${esc(new Date().toLocaleDateString())}
  </div>
  ${sessionOutput(state).sections.map(section => `<h2>${esc(section.title)}</h2><pre>${esc(section.content)}</pre>`).join("")}
  <p style="margin-top:2rem;color:#999;font-size:0.75rem;">Generated by Litigant AI — Don't just ask AI. Put the question on trial.</p>
</body>
</html>`;

  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => { w.print(); }, 400);
}

export async function exportDocx(state: SessionState): Promise<void> {
  const { Document, Paragraph, TextRun, HeadingLevel, Packer, AlignmentType } = await import("docx");
  const sections: DocParagraph[] = [
    new Paragraph({ text: "Litigant AI Session Report", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({
      children: [
        new TextRun({ text: "Question: ", bold: true }),
        new TextRun({ text: state.question }),
      ],
    }),
    ...(state.template
      ? [new Paragraph({ children: [new TextRun({ text: "Template: ", bold: true }), new TextRun({ text: state.template.title })] })]
      : []),
    new Paragraph({
      children: [
        new TextRun({ text: "AI review: ", bold: true }),
        new TextRun({ text: `${confidenceLabel(state.confidence)}` }),
        new TextRun({ text: "   Credits Used: ", bold: true }),
        new TextRun({ text: String(state.creditsUsed) }),
        new TextRun({ text: "   Date: ", bold: true }),
        new TextRun({ text: new Date().toLocaleDateString() }),
      ],
    }),
    new Paragraph({ text: "" }),
    ...sessionOutput(state).sections.flatMap(section => [
      new Paragraph({text: section.title, heading: HeadingLevel.HEADING_2}),
      ...section.content.split("\n").map(line => new Paragraph({text: line, alignment: AlignmentType.LEFT})),
      new Paragraph({text: ""}),
    ]),
    new Paragraph({
      children: [new TextRun({ text: "Generated by Litigant AI — Don't just ask AI. Put the question on trial.", italics: true, color: "888888" })],
    }),
  ];

  const doc = new Document({ sections: [{ children: sections }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `brain-session-${Date.now()}.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportJsPdf(state: SessionState): Promise<{ wasTrimmed: boolean }> {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addText(
    text: string,
    opts: { size?: number; bold?: boolean; color?: [number, number, number]; wrap?: boolean; gap?: number } = {}
  ) {
    const { size = 10, bold = false, color = [20, 20, 20], wrap = true, gap = 4 } = opts;
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines: string[] = wrap ? doc.splitTextToSize(text || "", contentW) : [text];
    lines.forEach((line: string) => {
      if (y + 6 > pageH - margin) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += size * 0.45;
    });
    y += gap;
  }

  function addSection(title: string, body: string) {
    if (y + 20 > pageH - margin) { doc.addPage(); y = margin; }
    addText(title, { size: 12, bold: true, color: [0, 150, 60], gap: 2 });
    doc.setDrawColor(0, 150, 60);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 3;
    addText(body || "—", { size: 9.5, color: [40, 40, 40], gap: 6 });
  }

  addText("Litigant AI — Session Report", { size: 18, bold: true, color: [0, 150, 60], gap: 2 });
  addText(`AI review: ${confidenceLabel(state.confidence)}  ·  Credits: ${state.creditsUsed}  ·  ${new Date().toLocaleDateString()}`, {
    size: 9, color: [100, 100, 100], gap: 6,
  });
  addText(`Question: ${state.question}`, { size: 10, bold: true, gap: 8 });

  let wasTrimmed = false;
  for (const section of sessionOutput(state).sections) {
    const trimmed = applyPdfTrimGuard(section.content);
    wasTrimmed ||= trimmed.wasTrimmed;
    addSection(section.title, trimmed.safeText);
  }

  doc.save(`brain-session-${Date.now()}.pdf`);
  return { wasTrimmed };
}
