// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/CommandRoom.tsx": () => import("../components/mockups/landing-variants/CommandRoom.tsx"),
  "./components/mockups/landing-variants/IntelligenceFeed.tsx": () => import("../components/mockups/landing-variants/IntelligenceFeed.tsx"),
  "./components/mockups/landing-variants/VerdictTheatre.tsx": () => import("../components/mockups/landing-variants/VerdictTheatre.tsx")
};
